-- MySQL Script generated by MySQL Workbench
-- Thu Oct  1 14:48:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- DATABASE esquema_certificacion
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `esquema_certificacion` DEFAULT CHARACTER SET utf8 ;
USE `esquema_certificacion` ;

-- -----------------------------------------------------
-- Table `esquema_certificacion`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_certificacion`.`usuarios` (
	`id_usuario` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(30) NOT NULL,
	`apellido` VARCHAR(50) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`password_hash` VARCHAR(255) NOT NULL,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_usuario`),
	UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_certificacion`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_certificacion`.`generos` (
	`id_genero` INT NOT NULL AUTO_INCREMENT,
	`nombre_genero` VARCHAR(50) NOT NULL,
	`descripcion_genero` TEXT NOT NULL,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_certificacion`.`libros_de_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_certificacion`.`libros_de_usuario` (
	`id_libro_user` INT NOT NULL AUTO_INCREMENT,
	`titulo_libro` VARCHAR(100) NOT NULL,
	`descripcion_libro` TEXT NOT NULL,
	`autor` VARCHAR(150) NOT NULL,
	`fecha_publicacion` DATE NOT NULL,
	`favoritos` INT NOT NULL,
	`id_usuario` INT NOT NULL,
	`id_genero` INT NOT NULL,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_libro_user`),
	INDEX `fk_libros_de_usuario_usuarios_idx` (`id_usuario` ASC) VISIBLE,
	INDEX `fk_libros_de_usuario_generos1_idx` (`id_genero` ASC) VISIBLE,
	CONSTRAINT `fk_libros_de_usuario_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `esquema_certificacion`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_libros_de_usuario_generos1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `esquema_certificacion`.`generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `esquema_certificacion`.`libros_comunidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_certificacion`.`libros_comunidad` (
	`id_libro_comunidad` INT NOT NULL AUTO_INCREMENT,
	`titulo_libro` VARCHAR(100) NOT NULL,
	`descripcion` TEXT NOT NULL,
	`autor` VARCHAR(150) NOT NULL,
	`fecha_publicacion` DATE NOT NULL,
	`favoritos` INT NOT NULL,
	`id_genero` INT NOT NULL,
	`id_usuario` INT NOT NULL,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id_libro_comunidad`),
	INDEX `fk_libros_comunidad_generos1_idx` (`id_genero` ASC) VISIBLE,
	INDEX `fk_libros_comunidad_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
    CONSTRAINT `fk_libros_comunidad_generos1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `esquema_certificacion`.`generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
	CONSTRAINT `fk_libros_comunidad_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `esquema_certificacion`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;